---

application:
  client-origin-url: ${env.CLIENT_ORIGIN_URL:http://localhost:4040}

server:
  error:
    whitelabel:
      enabled: false
  port: ${env.PORT:6060}

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

...
